### PR TITLE
Fix Ruby 3 compatibility issues

### LINKED ISSUE #79: ruby 3 incompatibility
Due to the previously-deprecated way args are passed in and mixed with kwargs, this is now throwing a ruby 3 error: https://github.com/sirupsen/airrecord/blob/master/lib/airrecord/faraday_rate_limiter.rb#L9

Any chance you guys can update this gem to work with the new kwarg standards?

### PR DESCRIPTION
**Pull request by courtsimas**
Closes #79 

Previously, anyone using the airrecord gem, couldn't upgrade their codebase to ruby 3 without errors. This adapts the Faraday Middleware (FaradayRateLimiter) initializer to just use the double splat, and updated some of the table code and tests to only use kwargs, instead of a mix. I didn't modify the travis.yml file, but I can if needed.

### CODE REVIEW

**Comment by Meekohi** [comment]
Was surprised to see all the tests change:
```
-    tea = Tea.new("Name" => "Dong Ding", "Brews" => ["rec2", "rec1"])
+    tea = Tea.new(fields: {"Name" => "Dong Ding", "Brews" => ["rec2", "rec1"]})
```

Is that new syntax required? Is this a big breaking change?

**Comment by courtsimas** [comment]
I can rework it but the table objects (tea, etc) have mixed keyword args and normal args and that’s not allowed so I converted them to just use kwargs. If you want, I can send them in as double splats as well. The tests failed in ruby 3, so one way or another they’ll have to change but the question is which approach you guys prefer I take.

**Comment by Meekohi** [comment]
Yeah I'm not opposed to this necessarily -- I'm just trying to figure out if this is an "all your existing code will break, need to do a migration" situation or if we can retain the same interface.

**Comment by Meekohi** [comment]
For anyone else digging, this is the relevant change in ruby 3: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by courtsimas** [comment]
@Meekohi Right... either we move people to forcing them to send some of their params in the `new` initializer in a hash, or we force them to add `fields:` 

I'm open to other suggestions and will modify as necessary.

**Comment by Meekohi** [comment]
Thanks, I understand this better now. I'll let others chime in, but I do think we should stick to the ActiveRecord conventions where possible, so 
`Tea.new("Name" => "Dong Ding", "Brews" => ["rec2", "rec1"])`
should do what you expect, and not need the explicit `{}`.

Proposal: I'm wondering what if we just make a separate option with one argument ` def initialize(fields)` that handles the "normal flow" I imagine 90% of people are using and all the docs show, and then we update the `id`/`created_at` syntax to require the explicit `{}`:

```
Tea.new("Name" => "Dong Ding", "Brews" => ["rec2", "rec1"]) # ok
Tea.new({"Name" => "Dong Ding", "Brews" => ["rec2", "rec1"]}) # ok
Tea.new({"Name" => "Dong Ding", "Brews" => ["rec2", "rec1"])}, id: 'id123', created_at: Time.now) # ok
Tea.new("Name" => "Dong Ding", "Brews" => ["rec2", "rec1"]), id: 'id123', created_at: Time.now) # Wrong Number of Arguments
```
This still causes a breaking change for anyone using the second syntax, but I don't suspect that is super common probably?

P.S.
I also thought some about if we could support ruby 3 without any breaking change in the interface... I guess you could do something like keep the 3 argument version and include a catch-all version:
```
def initialize(obj)
      @id = obj.id
      self.created_at = obj.created_at
      self.fields = obj.reject{|k,v| k.include? "created_at", "id"}
    end
```
but this will break if you have a field named `created_at` in your Airtable table, which seems like it might happen with some frequency.

**Comment by courtsimas** [comment]
> This still causes a breaking change for anyone using the second syntax, but I don't suspect that is super common probably?

Agreed, I don't think that's common; and proper documentation around continuing to support that functionality would be trivial.

> but this will break if you have a field named created_at in your Airtable table, which seems like it might happen with some frequency.

We actually do use Airtable like that so that would break some of our stuff ... and I'm not sure if I could guess as to how common that is. 🤷 

I'm fine with tackling/providing support/discussing whatever you guys feel is best.

**Comment by sirupsen** [comment]
Wow, I haven't dug much into Ruby 3 -- that change is going to be a nightmare for upgrading code-bases. 😱 Either way, we don't have to make upgrading Airrecord painful. It's possible to remain fully backwards compatible. I went ahead and did this in master, releasing it as a new patch version 1.0.6 which you'll find now on Rubygems.

Thanks a lot for the discussion in here and the relevant links, made it quick to fix this. 

https://github.com/sirupsen/airrecord/commit/646869268f22d28070e186b49a2135bf8f72fc39

**Pull request closed without merging**
