### PR TITLE
Add support for multiple parameters ordering. 

### PR DESCRIPTION
**Pull request by socjopata**
It seems that the airtable expects multiple occurrences of the sort parameter in an API call per sort instruction, instead of one sort key pointing to an array of sort directives. See https://codepen.io/airtable/full/rLKkYB where you can generate an example URL.

P.S I tried to write a test for the introduced case, but your approach and setup is so much different to mine. The test would be so much easier (if possible) if you leveraged Webmock. The assertion could be made on the generated and suppressed request URL, fired up by Faraday.

### CODE REVIEW

**Comment by sirupsen** [comment]
Hey, do you still need this?

**Comment by socjopata** [comment]
Hi @sirupsen , actually no, the requirements of the given project has changed and I do not longer use this feature. However it might be a good idea to mention in the docs that multiple sorting parameters are not supported by your gem (it took me a while before I discovered how the Airtable actually works in this context)

**Comment by sirupsen** [comment]
@socjopata it'd be great to have it make it into 1.0.0 we're about to release if you wouldn't mind rebasing and making the tests pass? ❤️

**Comment by sirupsen** [comment]
@chrisfrank @Meekohi if any of you have cycles, this'd be good to land.

**Comment by Meekohi** [comment]
Doesn't this
```
options["sort"] = [{ field: field.to_s, direction: direction }]
```
just overwrite the "sort" parameter? So this only searches by the "last sort field" and ignores the others?

**Comment by Meekohi** [comment]
I think it should be like this flavor?
```
options["sort[0]"] = [{ field: field1.to_s, direction: direction1 }]
options["sort[1]"] = [{ field: field2.to_s, direction: direction2 }]
```
but someone should test and verify.

**Comment by chrisfrank** [comment]
@Meekohi I think you're right that the code in this PR will ignore all but the last sort parameter, and that the way Airtable parses query params into arrays is odd, at least compared to the way a Rails or Rack app does. I'll have time tomorrow and this weekend to dig into this.

@sirupsen would you prefer we keep working from forks, or is it okay for us to open feature branches in your repo? I think I'll have a clearer picture of the 1.0 roadmap if we start branches, but obviously I want to respect your preferred workflow.

**Comment by socjopata** [comment]
Life proved again, that the code without the proper specs, doesn't work too well! Mea culpa, my bad here. But like I said, I didn't find it easy to add a proper specs, using the existing spec suite. I think the good idea might be to actually test and validate the links generated by https://codepen.io/airtable/full/rLKkYB vs some existing table on the AT and decide what's next... because I'm kinda sure, that I received different output using codepen, several months ago, when I proposed the solution included in this pull request.

**Comment by sirupsen** [comment]
> @sirupsen would you prefer we keep working from forks, or is it okay for us to open feature branches in your repo? I think I'll have a clearer picture of the 1.0 roadmap if we start branches, but obviously I want to respect your preferred workflow.

Yes :)

@socjopata I understand that you don't find the test suite ideal. It uses vanilla mocks and I haven't had any issues with it. It seems you have a better idea for how this might look? I'd be happy to take a look at a PR where you show this.

**Comment by chrisfrank** [comment]
Closing this as we're now tracking it in [#37](https://github.com/sirupsen/airrecord/pull/37). Thanks everyone!

**Pull request closed without merging**
