### PR TITLE
Switch back to default Faraday encoder and change list-records call to POST

### LINKED ISSUE #95: Accelerated need to limit large url requests to “list records”, with alternative POST version
Hi! Fred here again, from the Airtable API team. Another update is that as part of recent infrastructure improvements to airtable.com, we needed to accelerate enforcement of rejecting any requests whose request URLs exceed 16k characters. The changes described below are in effect today.

* Q: What endpoints does this affect?
    * The 16k character limit applies to **all current and future API request URLs**
    * Based on our internal audit of current usage, this primary impacts the “list records” endpoint, which is a GET request to `/v0/{baseId}/{tableIdOrName}` (https://airtable.com/developers/web/api/list-records)
* Q: What is the impact of this change?
    * The vast majority of our API requests have remained well under the 16k character limit, and would not be affected
    * However, requests exceeding this limit will now be rejected, so we expect some calls to now require an update to handle the large cases. For example, requests whose query parameter for `filterbyFormula` is long enough to make the overall URL length to exceed that character limit
    * Therefore, we recommend either switching entirely to the alternative detailed below, or switching to it when you can detect that a request URL will exceed the 16k character limit
* Q: What is the alternative?
    * APIs can instead make a POST request to `/v0/{baseId}/{tableIdOrName}/listRecords`, and encode the query params as the body of that POST request. We currently still require two parameters to remain as query params, `timeZone` and `userLocale`; you can see the full details and examples here: https://support.airtable.com/docs/enforcement-of-url-length-limit-for-web-api-requests 
* Q: Why the urgency for this change?
    * I apologize for the inconvenience due to the accelerated timeline here. While we originally planned to start this enforcement in January 2023, we needed to deploy this change recently last week, as part of required infrastructure improvements to maintain the stability of our public API

### PR DESCRIPTION
**Pull request by theblang**
See comments below. I smoke tested:

1. `all` (with a single and multiple value `fields` array)
2. `find`

### CODE REVIEW

**Comment by Meekohi** [comment]
Looks solid to me but I'm not in a position to test this library myself anymore. @theblang if you're confident I'll go ahead and merge?

**Comment by Meekohi** [comment]
@sirupsen maybe you can do a quick smoke test on this?

**Comment by theblang** [comment]
@Meekohi About to do some heavy smoke testing in our internal code that uses this PR's changes, so I'll report back once I'm finished!

**Comment by sirupsen** [comment]
yeah I don't have anything in production on airrrecord anymore to smoke test with unfortunately

**Comment by theblang** [comment]
I just noticed that Development section of the sidebar! So I removed "Fixes #95" from the commit message. But I think one of you will need to add it to Development?

**Comment by Meekohi** [comment]
Sounds like I nominate @theblang to be the new maintainer ;D I'm gonna go ahead and merge.

**Comment by theblang** [comment]
> Sounds like I nominate @theblang to be the new maintainer ;D I'm gonna go ahead and merge.

Delayed response, haha, but I'm happy to help with maintaining this gem! We use Airtable extensively from our Rails stack.

**Comment by Meekohi** [comment]
+1 to adding @theblang to the maintainers -- I'm not actively using this in production anymore so happy to help with small things but can't really review big PRs and etc.

**Pull request merged**
